Reset your password for Marvin @ ${config.institutionAcronym}
Hi ${academic.name}...

I received a request to reset your password. Don't pretend you want to talk to me, I know you hate me.

If you didn't make the request, just ignore this email. Otherwise, you can reset your password using this link:

${config.baseURL}/servlet/changePassword/${academic.passwordCode}

I'd give you advice, but you wouldn't listen. No one ever does.

- Marvin @ ${config.institutionAcronym}
- ${config.baseURL}
